module.exports = [
  [ '@charlesstover/hsl2rgb' ],
  [ '@charlesstover/quicksort' ],
  [ '@gamingmedley/konami.js' ],
  [ 'deep-proxy-polyfill' ],
  [ 'delimiter' ],
  [ 'fetch-action-creator', 'async-action', 'thunk-action-creator' ],
  [ 'fetch-suspense' ],
  [ 'mssql-query-builder' ],
  [ 'pluralsight-score' ],
  [ 'rainbow-gradient' ],
  [ 'react-innertext', 'jsx-inner-text' ],
  [ 'react-mui-tooltip' ],
  [ 'react-multi-context' ],
  [ 'react-object-prop' ],
  [ 'react-portfolio' ],
  [ 'react-quotes-carousel', 'react-quotes' ],
  [ 'react-rainbow-text' ],
  [ 'reactn' ],
  [ 'rn-webview' ],
  [ 'use-dimensions' ],
  [ 'use-force-update' ],
  [ 'use-react-router' ],
  [ 'with-router' ],
  [ null, '@charlesstover/electron-transitions', '@charlesstover/password-generator', '@charlesstover/radix', '@charlesstover/rainbow-text', '@charlesstover/spritesheet2gif' ]
];
